const { BigNumber } = require("@ethersproject/bignumber");
const { ethers } = require("hardhat");


export const keyPrefixes = {
    ring: "RING",
    hand:"HAND",
    companion:"COMPANION",
    power:"POWER",
    weapon:"WEAPON"   
}
export const arrays = {
    Traits: {
       
   weapon:
   [
       "Warhammer",
       "Quarterstaff",
       "Maul",
       "Mace",
       "Club",
       "Katana",
       "Falchion",
       "Scimitar",
       "Long Sword",
       "Short Sword",
       "Ghost Wand",
       "Grave Wand",
       "Bone Wand",
       "Wand",
       "Grimoire",
       "Chronicle",
       "Tome",
       "Book"
   ],
   companion:[
       "Black Cat",
       "Dragon",
       "Lucifer",
       "Baphomet",
       "Elf",
       "Orc",
       "Demogorgon",
       "Cenobite",
       "Cerberus",
       "Ghost",
       "Werewolf",
       "Leviathan",
       "Kraken",
       "Zombie",
       "Mummy"
   ],
   power:[
    "Telepathy",
   "Clairvoiance",
   "Can Talk To Ghosts",
   "Remote Viewing",
   "Summoning Demons",
   "Taming Dragons",
   "Mind Reading",
   "Summoing Angels",
   "Immortality",
   "Hearing Nature",
   "Casting Magic Spells",
   "Witchcraft/Wizardry",
   "Reviving The Dead",
   "Invisibility",
   "Palm reading"],
    hand: [
       "Holy Gauntlets",
       "Ornate Gauntlets",
       "Gauntlets",
       "Chain Gloves",
       "Heavy Gloves",
       "Demon's Hands",
       "Dragonskin Gloves",
       "Studded Leather Gloves",
       "Hard Leather Gloves",
       "Leather Gloves",
       "Divine Gloves",
       "Silk Gloves",
       "Wool Gloves",
       "Linen Gloves",
       "Gloves"
    ],
    rings: [ 
       "Gold Ring",
       "Silver Ring",
       "Bronze Ring",
       "Platinum Ring",
       "Titanium Ring"],
   
   suffix: [ "of Power",
   "of Giants",
   "of Titans",
   "of Skill",
   "of Perfection",
   "of Brilliance",
   "of Enlightenment",
   "of Protection",
   "of Anger",
   "of Rage",
   "of Fury",
   "of Vitriol",
   "of the Fox",
   "of Detection",
   "of Reflection",
   "of the Twins"],
   
   nameSuffix: [ "Bane",
   "Root",
   "Bite",
   "Song",
   "Roar",
   "Grasp",
   "Instrument",
   "Glow",
   "Bender",
   "Shadow",
   "Whisper",
   "Shout",
   "Growl",
   "Tear",
   "Peak",
   "Form",
   "Sun",
   "Moon"],
   
   namePrefix: [
       "Agony",
       "Apocalypse",
       "Armageddon",
       "Beast",
       "Behemoth",
       "Blight",
       "Blood",
       "Bramble",
       "Brimstone",
       "Brood",
       "Carrion",
       "Cataclysm",
       "Chimeric",
       "Corpse",
       "Corruption",
       "Damnation",
       "Death",
       "Demon",
       "Dire",
       "Dragon",
       "Dread",
       "Doom",
       "Dusk",
       "Eagle",
       "Empyrean",
       "Fate",
       "Foe",
       "Gale",
       "Ghoul",
       "Gloom",
       "Glyph",
       "Golem",
       "Grim",
       "Hate",
       "Havoc",
       "Honour",
       "Horror",
       "Hypnotic",
       "Kraken",
       "Loath",
       "Maelstrom",
       "Mind",
       "Miracle",
       "Morbid",
       "Oblivion",
       "Onslaught",
       "Pain",
       "Pandemonium",
       "Phoenix",
       "Plague",
       "Rage",
       "Rapture",
       "Rune",
       "Skull",
       "Sol",
       "Soul",
       "Sorrow",
       "Spirit",
       "Storm",
       "Tempest",
       "Torment",
       "Vengeance",
       "Victory",
       "Viper",
       "Vortex",
       "Woe",
       "Wrath",
       "Light's",
       "Shimmering"
   ]
   }
    }